pipeline {
     agent any
     stages {
        stage("Cache Cleaning") {
            steps {
              sh "sudo docker system prune --force --all --volumes"
              sh "sudo find /tmp -type f -atime +10 -delete"
              sh "sudo pwd"
            }
        }
        stage("Build") {
          steps {
            dir('./code/microsservice/emailapi') {
              sh "sudo docker build -t sallu-emailapi ."
            }
          }
        }
        stage("Deploy") {
          steps {
            dir('./code/microsservice/emailapi') {
              sh "sudo docker run -p 80:8080 sallu-emailapi & exit 0"
            }
          }
        }
    }
}