runtime: java11 
env: standard 
runtime_config: 
  jdk: openjdk11
env_variables: 
  SPRING_PROFILES_ACTIVE: 
manipuladores de "produção" : 
- url: /.* 
  script: este campo é obrigatório, mas ignorado 
manual_scaling: 
  instances: 1