pipeline {
     agent any
     stages {
        stage("Cache Cleaning") {
            steps {
                sh "sudo docker system prune"
                sh "sudo yarn cache clean"
                sh "sudo find /tmp -type f -atime +10 -delete"
                sh "sudo pwd"
            }
        }

        stage("Build") {
            steps {
                sh "cd ./code/web"
                sh "sudo pwd"
                sh "sudo ls"
                sh "sudo yarn install"
                sh "sudo cp ./prod.env ./.env"
                sh "sudo yarn build"
            }
        }
        stage("Deploy") {
            steps {
                sh "sudo rm -rf /usr/share/nginx/html/*"
                sh "sudo cp -r ./build/* /usr/share/nginx/html"
            }
        }
    }
}