pipeline {
     agent any
     stages {
        stage("Cache Cleaning") {
            steps {
              sh "sudo docker system prune --force --all --volumes"
              sh "sudo yarn cache clean"
              sh "sudo find /tmp -type f -atime +10 -delete"
              sh "sudo pwd"
            }
        }
        stage("Build") {
          steps {
            dir('./code/web') {
              sh "sudo docker build -t sallu-web ."
            }
          }
        }
        stage("Deploy") {
          steps {
            dir('./code/web') {
              sh "sudo docker run -p 80:80 sallu-web & exit 0"
            }
          }
        }
    }
}